file_format: "0.1" # Sửa lỗi Missing property

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  # Thêm processor để chuẩn hóa nhãn cho Backend
  resource:
    attributes:
      - key: app
        value: "auraeyes-api"
        action: insert
      - key: service_name
        value: "auraeyes-api"
        action: insert
      - key: environment
        value: "production"
        action: insert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, debug]
