CREATE TABLE public.AiScreenings (
  Id uuid NOT NULL,
  PatientId uuid NOT NULL,
  ModelVersion character varying NOT NULL,
  ProcessedAt timestamp with time zone,
  RawJsonOutput jsonb,
  IsActive boolean NOT NULL DEFAULT true,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT AiScreenings_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_AiScreenings_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id)
);
CREATE TABLE public.AppointmentSlots (
  Id uuid NOT NULL,
  ScheduleTemplateId uuid NOT NULL,
  Date date NOT NULL,
  StartTime time without time zone NOT NULL,
  EndTime time without time zone NOT NULL,
  Status character varying NOT NULL,
  OphthalId uuid,
  Cost numeric,
  MaxCapacity integer NOT NULL DEFAULT 1,
  BookedCount integer NOT NULL DEFAULT 0,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT AppointmentSlots_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_AppointmentSlots_ScheduleTemplates_ScheduleTemplateId FOREIGN KEY (ScheduleTemplateId) REFERENCES public.ScheduleTemplates(Id)
);
CREATE TABLE public.Appointments (
  Id uuid NOT NULL,
  PatientId uuid NOT NULL,
  AppointmentSlotId uuid NOT NULL,
  Status character varying NOT NULL,
  VisitReason character varying,
  CancelledBy uuid,
  CancellationReason character varying,
  RequestedDoctorId uuid,
  PricingType character varying NOT NULL,
  Price numeric NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Appointments_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_Appointments_AppointmentSlots_AppointmentSlotId FOREIGN KEY (AppointmentSlotId) REFERENCES public.AppointmentSlots(Id),
  CONSTRAINT FK_Appointments_Ophthalmologists_RequestedDoctorId FOREIGN KEY (RequestedDoctorId) REFERENCES public.Ophthalmologists(Id),
  CONSTRAINT FK_Appointments_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id)
);
CREATE TABLE public.AspNetRoleClaims (
  Id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  RoleId uuid NOT NULL,
  ClaimType text,
  ClaimValue text,
  CONSTRAINT AspNetRoleClaims_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_AspNetRoleClaims_AspNetRoles_RoleId FOREIGN KEY (RoleId) REFERENCES public.AspNetRoles(Id)
);
CREATE TABLE public.AspNetRoles (
  Id uuid NOT NULL,
  Description text,
  CreatedAt timestamp with time zone NOT NULL,
  IsActive boolean NOT NULL,
  Name character varying,
  NormalizedName character varying,
  ConcurrencyStamp text,
  CONSTRAINT AspNetRoles_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.AspNetUserClaims (
  Id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  UserId uuid NOT NULL,
  ClaimType text,
  ClaimValue text,
  CONSTRAINT AspNetUserClaims_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_AspNetUserClaims_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES public.AspNetUsers(Id)
);
CREATE TABLE public.AspNetUserLogins (
  LoginProvider text NOT NULL,
  ProviderKey text NOT NULL,
  ProviderDisplayName text,
  UserId uuid NOT NULL,
  CONSTRAINT AspNetUserLogins_pkey PRIMARY KEY (LoginProvider, ProviderKey),
  CONSTRAINT FK_AspNetUserLogins_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES public.AspNetUsers(Id)
);
CREATE TABLE public.AspNetUserRoles (
  UserId uuid NOT NULL,
  RoleId uuid NOT NULL,
  CONSTRAINT AspNetUserRoles_pkey PRIMARY KEY (UserId, RoleId),
  CONSTRAINT FK_AspNetUserRoles_AspNetRoles_RoleId FOREIGN KEY (RoleId) REFERENCES public.AspNetRoles(Id),
  CONSTRAINT FK_AspNetUserRoles_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES public.AspNetUsers(Id)
);
CREATE TABLE public.AspNetUserTokens (
  UserId uuid NOT NULL,
  LoginProvider text NOT NULL,
  Name text NOT NULL,
  ExpiryDate timestamp with time zone,
  DeviceInfo text,
  IpAddress text,
  IsRevoked boolean NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  RevokedAt timestamp with time zone,
  ReasonRevoked text,
  Value text,
  CONSTRAINT AspNetUserTokens_pkey PRIMARY KEY (UserId, LoginProvider, Name),
  CONSTRAINT FK_AspNetUserTokens_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES public.AspNetUsers(Id)
);
CREATE TABLE public.AspNetUsers (
  Id uuid NOT NULL,
  FullName character varying NOT NULL,
  Address character varying,
  Gender integer,
  DateOfBirth timestamp with time zone,
  AvatarUrl character varying,
  CitizenId character varying,
  IsActive boolean NOT NULL,
  IsDeleted boolean NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  LastLoginAt timestamp with time zone,
  DeletedAt timestamp with time zone,
  MustUpdateProfile boolean NOT NULL DEFAULT false,
  UserName character varying,
  NormalizedUserName character varying,
  Email character varying,
  NormalizedEmail character varying,
  EmailConfirmed boolean NOT NULL,
  PasswordHash text,
  SecurityStamp text,
  ConcurrencyStamp text,
  PhoneNumber text,
  PhoneNumberConfirmed boolean NOT NULL,
  TwoFactorEnabled boolean NOT NULL,
  LockoutEnd timestamp with time zone,
  LockoutEnabled boolean NOT NULL,
  AccessFailedCount integer NOT NULL,
  CONSTRAINT AspNetUsers_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.AuditLogs (
  Id uuid NOT NULL,
  UserId uuid,
  Action character varying NOT NULL,
  EntityName character varying NOT NULL,
  EntityId character varying,
  OldValue jsonb,
  NewValue jsonb,
  IpAddress character varying,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT AuditLogs_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.Certificates (
  Id uuid NOT NULL,
  OphthalmologistId uuid NOT NULL,
  Type integer NOT NULL,
  DegreeLevel integer,
  Name character varying NOT NULL,
  IssuingAuthority character varying,
  IssuedDate timestamp with time zone NOT NULL,
  ExpiryDate timestamp with time zone,
  CertificateUrl character varying,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Certificates_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_Certificates_Ophthalmologists_OphthalmologistId FOREIGN KEY (OphthalmologistId) REFERENCES public.Ophthalmologists(Id)
);
CREATE TABLE public.ChatMessages (
  Id uuid NOT NULL,
  ConversationId uuid NOT NULL,
  SenderUserId uuid NOT NULL,
  Message character varying NOT NULL,
  IsRead boolean NOT NULL DEFAULT false,
  SentAt timestamp with time zone NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT ChatMessages_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_ChatMessages_Conversations_ConversationId FOREIGN KEY (ConversationId) REFERENCES public.Conversations(Id)
);
CREATE TABLE public.ClinicFeedback (
  Id uuid NOT NULL,
  PatientId uuid NOT NULL,
  AppointmentId uuid NOT NULL,
  Rating integer NOT NULL CHECK ("Rating" >= 1 AND "Rating" <= 5),
  Comment character varying,
  DoctorId uuid,
  StaffId uuid,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL,
  CONSTRAINT ClinicFeedback_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_ClinicFeedback_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id),
  CONSTRAINT FK_ClinicFeedback_Appointments_AppointmentId FOREIGN KEY (AppointmentId) REFERENCES public.Appointments(Id),
  CONSTRAINT FK_ClinicFeedback_ClinicStaffs_StaffId FOREIGN KEY (StaffId) REFERENCES public.ClinicStaffs(Id),
  CONSTRAINT FK_ClinicFeedback_Ophthalmologists_DoctorId FOREIGN KEY (DoctorId) REFERENCES public.Ophthalmologists(Id)
);
CREATE TABLE public.ClinicStaffs (
  Id uuid NOT NULL,
  UserId uuid NOT NULL,
  SubRoles character varying NOT NULL,
  Department character varying,
  EmployeeCode character varying,
  Phone character varying,
  IsActive boolean NOT NULL DEFAULT true,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT ClinicStaffs_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.ConsultationSessions (
  Id uuid NOT NULL,
  PatientId uuid NOT NULL,
  OphthalmologistId uuid,
  AiScreeningId uuid,
  Type character varying NOT NULL,
  Status character varying NOT NULL,
  ChatStatus character varying NOT NULL,
  Price numeric NOT NULL,
  AppointmentTime timestamp with time zone,
  StartTime timestamp with time zone,
  EndTime timestamp with time zone,
  LastActivityAt timestamp with time zone NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT ConsultationSessions_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_ConsultationSessions_AiScreenings_AiScreeningId FOREIGN KEY (AiScreeningId) REFERENCES public.AiScreenings(Id),
  CONSTRAINT FK_ConsultationSessions_Ophthalmologists_OphthalmologistId FOREIGN KEY (OphthalmologistId) REFERENCES public.Ophthalmologists(Id),
  CONSTRAINT FK_ConsultationSessions_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id)
);
CREATE TABLE public.Conversations (
  Id uuid NOT NULL,
  OphthalmologistId uuid NOT NULL,
  ConsultationSessionId uuid NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Conversations_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_Conversations_ConsultationSessions_ConsultationSessionId FOREIGN KEY (ConsultationSessionId) REFERENCES public.ConsultationSessions(Id),
  CONSTRAINT FK_Conversations_Ophthalmologists_OphthalmologistId FOREIGN KEY (OphthalmologistId) REFERENCES public.Ophthalmologists(Id)
);
CREATE TABLE public.HealthRoadmapSteps (
  Id uuid NOT NULL,
  RoadmapId uuid NOT NULL,
  Title character varying NOT NULL,
  Description character varying,
  StepType character varying NOT NULL,
  PlannedDate date NOT NULL,
  Status character varying NOT NULL,
  CreatedByDoctorId uuid NOT NULL,
  CreatedFromVisitId uuid,
  CompletedAt timestamp with time zone,
  OrderIndex integer NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT HealthRoadmapSteps_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_HealthRoadmapSteps_HealthRoadmaps_RoadmapId FOREIGN KEY (RoadmapId) REFERENCES public.HealthRoadmaps(Id),
  CONSTRAINT FK_HealthRoadmapSteps_Ophthalmologists_CreatedByDoctorId FOREIGN KEY (CreatedByDoctorId) REFERENCES public.Ophthalmologists(Id),
  CONSTRAINT FK_HealthRoadmapSteps_PatientVisits_CreatedFromVisitId FOREIGN KEY (CreatedFromVisitId) REFERENCES public.PatientVisits(Id)
);
CREATE TABLE public.HealthRoadmaps (
  Id uuid NOT NULL,
  PatientId uuid NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT HealthRoadmaps_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_HealthRoadmaps_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id)
);
CREATE TABLE public.InternalGroupChats (
  Id uuid NOT NULL,
  Name character varying,
  Type integer NOT NULL,
  ConsultationSessionId uuid,
  MeetingLink text,
  CalendarEventId text,
  CreatorId uuid NOT NULL,
  CreatorType integer NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL,
  CONSTRAINT InternalGroupChats_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.InternalGroupMembers (
  Id uuid NOT NULL,
  GroupId uuid NOT NULL,
  MemberId uuid NOT NULL,
  MemberType integer NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL,
  CONSTRAINT InternalGroupMembers_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_InternalGroupMembers_InternalGroupChats_GroupId FOREIGN KEY (GroupId) REFERENCES public.InternalGroupChats(Id)
);
CREATE TABLE public.InternalGroupMessages (
  Id uuid NOT NULL,
  GroupId uuid NOT NULL,
  SenderId uuid NOT NULL,
  SenderType integer NOT NULL,
  Content text NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL,
  CONSTRAINT InternalGroupMessages_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_InternalGroupMessages_InternalGroupChats_GroupId FOREIGN KEY (GroupId) REFERENCES public.InternalGroupChats(Id)
);
CREATE TABLE public.MedicalDiagnoses (
  Id uuid NOT NULL,
  AiScreeningId uuid NOT NULL,
  DoctorId uuid NOT NULL,
  ConsultationSessionId uuid NOT NULL,
  DiagnosisCode character varying,
  CodingSystem character varying,
  ClinicalFindings character varying,
  SeverityLevel character varying,
  ConfidenceLevel numeric,
  TreatmentPlan character varying,
  Recommendations character varying,
  IsUrgent boolean NOT NULL DEFAULT false,
  Status character varying,
  FinalizedAt timestamp with time zone,
  LifestyleAdvice character varying,
  IsReferralNeeded boolean NOT NULL DEFAULT false,
  FollowUpDate timestamp with time zone,
  ConfirmedAt timestamp with time zone,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT MedicalDiagnoses_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_MedicalDiagnoses_AiScreenings_AiScreeningId FOREIGN KEY (AiScreeningId) REFERENCES public.AiScreenings(Id),
  CONSTRAINT FK_MedicalDiagnoses_ConsultationSessions_ConsultationSessionId FOREIGN KEY (ConsultationSessionId) REFERENCES public.ConsultationSessions(Id),
  CONSTRAINT FK_MedicalDiagnoses_Ophthalmologists_DoctorId FOREIGN KEY (DoctorId) REFERENCES public.Ophthalmologists(Id)
);
CREATE TABLE public.MedicalRecords (
  Id uuid NOT NULL,
  PatientId uuid NOT NULL,
  ConsultationSessionId uuid,
  PatientVisitId uuid,
  MedicalRecordNumber character varying NOT NULL,
  PdfUrl character varying,
  Status integer NOT NULL,
  AdministrativeDataJson text NOT NULL,
  ClinicalDataJson text NOT NULL,
  FinalDiagnosis text NOT NULL,
  TreatmentPlan text NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL,
  CONSTRAINT MedicalRecords_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_MedicalRecords_PatientVisits_PatientVisitId FOREIGN KEY (PatientVisitId) REFERENCES public.PatientVisits(Id),
  CONSTRAINT FK_MedicalRecords_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id),
  CONSTRAINT FK_MedicalRecords_ConsultationSessions_ConsultationSessionId FOREIGN KEY (ConsultationSessionId) REFERENCES public.ConsultationSessions(Id)
);
CREATE TABLE public.Notifications (
  Id uuid NOT NULL,
  UserId uuid NOT NULL,
  Title character varying NOT NULL,
  Message character varying NOT NULL,
  Type integer NOT NULL,
  ReferenceId uuid,
  IsRead boolean NOT NULL DEFAULT false,
  Payload jsonb,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Notifications_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.OphthalmologistLeaveRequests (
  Id uuid NOT NULL,
  OphthalmologistId uuid NOT NULL,
  StartDate date NOT NULL,
  EndDate date NOT NULL,
  Reason character varying NOT NULL,
  Status character varying NOT NULL,
  AdminNote character varying,
  ReviewedByAdminUserId uuid,
  ReviewedAt timestamp with time zone,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL,
  CONSTRAINT OphthalmologistLeaveRequests_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_OphthalmologistLeaveRequests_Ophthalmologists_Ophthalmologi~ FOREIGN KEY (OphthalmologistId) REFERENCES public.Ophthalmologists(Id)
);
CREATE TABLE public.Ophthalmologists (
  Id uuid NOT NULL,
  UserId uuid NOT NULL,
  Bio character varying,
  Phone character varying,
  EmploymentType character varying NOT NULL DEFAULT 'FullTime'::character varying,
  YearsOfExperience integer NOT NULL DEFAULT 0,
  LicenseUrl character varying,
  DegreeUrl character varying,
  RatingAverage numeric NOT NULL DEFAULT 0.0,
  RatingCount integer NOT NULL DEFAULT 0,
  ConsultationFee numeric NOT NULL DEFAULT 0.0,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Ophthalmologists_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.Orders (
  Id uuid NOT NULL,
  UserId uuid NOT NULL,
  AppointmentId uuid,
  TotalAmount numeric NOT NULL,
  DepositAmount numeric,
  Description text,
  Status character varying NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Orders_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_Orders_Appointments_AppointmentId FOREIGN KEY (AppointmentId) REFERENCES public.Appointments(Id)
);
CREATE TABLE public.PatientVisits (
  Id uuid NOT NULL,
  AppointmentId uuid,
  PatientId uuid NOT NULL,
  AssignedDoctorId uuid,
  CheckedInAt timestamp with time zone,
  StartedAt timestamp with time zone,
  CompletedAt timestamp with time zone,
  Status character varying NOT NULL,
  Notes character varying,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT PatientVisits_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_PatientVisits_Appointments_AppointmentId FOREIGN KEY (AppointmentId) REFERENCES public.Appointments(Id),
  CONSTRAINT FK_PatientVisits_Ophthalmologists_AssignedDoctorId FOREIGN KEY (AssignedDoctorId) REFERENCES public.Ophthalmologists(Id),
  CONSTRAINT FK_PatientVisits_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id)
);
CREATE TABLE public.Patients (
  Id uuid NOT NULL,
  UserId uuid,
  FullName character varying,
  PhoneNumber character varying,
  CitizenId character varying,
  DateOfBirth timestamp with time zone,
  GenderId integer,
  Address character varying,
  MedicalRecordNumber character varying,
  BMI numeric,
  DiseaseHistory character varying,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL,
  CONSTRAINT Patients_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.Payments (
  Id uuid NOT NULL,
  OrderId uuid NOT NULL,
  Amount numeric NOT NULL,
  Status character varying NOT NULL,
  Method character varying NOT NULL,
  PaidAt timestamp with time zone,
  PaymentOrderCode text,
  PaymentUrl text,
  ProviderTxnRef text,
  ProviderResponse text,
  Description text,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Payments_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_Payments_Orders_OrderId FOREIGN KEY (OrderId) REFERENCES public.Orders(Id)
);
CREATE TABLE public.Permissions (
  Id uuid NOT NULL,
  Name character varying NOT NULL,
  DisplayName character varying NOT NULL,
  Description character varying,
  Category character varying,
  IsActive boolean NOT NULL DEFAULT true,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT Permissions_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.PostAttachments (
  Id uuid NOT NULL,
  PostId uuid NOT NULL,
  Type character varying NOT NULL,
  FileName character varying NOT NULL,
  FileUrl character varying NOT NULL,
  MimeType character varying,
  FileSize bigint,
  DisplayOrder integer NOT NULL DEFAULT 0,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT PostAttachments_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_PostAttachments_ProfessionalPosts_PostId FOREIGN KEY (PostId) REFERENCES public.ProfessionalPosts(Id)
);
CREATE TABLE public.PostComments (
  Id uuid NOT NULL,
  PostId uuid NOT NULL,
  AuthorId uuid NOT NULL,
  AuthorType character varying NOT NULL,
  Content character varying NOT NULL,
  ParentCommentId uuid,
  ReplyCount integer NOT NULL DEFAULT 0,
  LikeCount integer NOT NULL DEFAULT 0,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT PostComments_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_PostComments_PostComments_ParentCommentId FOREIGN KEY (ParentCommentId) REFERENCES public.PostComments(Id),
  CONSTRAINT FK_PostComments_ProfessionalPosts_PostId FOREIGN KEY (PostId) REFERENCES public.ProfessionalPosts(Id)
);
CREATE TABLE public.PostReactions (
  Id uuid NOT NULL,
  PostId uuid NOT NULL,
  UserId uuid NOT NULL,
  Type character varying NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT PostReactions_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_PostReactions_ProfessionalPosts_PostId FOREIGN KEY (PostId) REFERENCES public.ProfessionalPosts(Id)
);
CREATE TABLE public.ProfessionalPosts (
  Id uuid NOT NULL,
  AuthorId uuid NOT NULL,
  AuthorType character varying NOT NULL,
  Content character varying NOT NULL,
  Category character varying NOT NULL,
  OriginalPostId uuid,
  IsRepost boolean NOT NULL DEFAULT false,
  RepostComment character varying,
  ReactionCount integer NOT NULL DEFAULT 0,
  CommentCount integer NOT NULL DEFAULT 0,
  RepostCount integer NOT NULL DEFAULT 0,
  ViewCount integer NOT NULL DEFAULT 0,
  AllowComments boolean NOT NULL DEFAULT true,
  IsHidden boolean NOT NULL DEFAULT false,
  HideReason character varying,
  IsInternalCase boolean NOT NULL DEFAULT false,
  ConsultationSessionId uuid,
  AiScreeningId uuid,
  PatientAge integer,
  PatientGender character varying,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT ProfessionalPosts_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_ProfessionalPosts_ProfessionalPosts_OriginalPostId FOREIGN KEY (OriginalPostId) REFERENCES public.ProfessionalPosts(Id)
);
CREATE TABLE public.RefreshTokens (
  Id uuid NOT NULL,
  TokenHash character varying NOT NULL,
  JwtId character varying NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  ExpiresAt timestamp with time zone NOT NULL,
  UsedAt timestamp with time zone,
  RevokedAt timestamp with time zone,
  RevokedReason character varying,
  ReplacedByTokenId uuid,
  DeviceInfo character varying,
  IpAddress character varying,
  UserId uuid NOT NULL,
  CONSTRAINT RefreshTokens_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_RefreshTokens_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES public.AspNetUsers(Id)
);
CREATE TABLE public.RetinalImages (
  Id uuid NOT NULL,
  PatientId uuid NOT NULL,
  AiScreeningId uuid,
  ImageUrl character varying NOT NULL,
  DeviceName character varying,
  EyeSide character varying NOT NULL,
  QualityScore numeric,
  CapturedAt timestamp with time zone NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT RetinalImages_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_RetinalImages_AiScreenings_AiScreeningId FOREIGN KEY (AiScreeningId) REFERENCES public.AiScreenings(Id),
  CONSTRAINT FK_RetinalImages_Patients_PatientId FOREIGN KEY (PatientId) REFERENCES public.Patients(Id)
);
CREATE TABLE public.RolePermissions (
  Id uuid NOT NULL,
  RoleId uuid NOT NULL,
  PermissionId uuid NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT RolePermissions_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_RolePermissions_AspNetRoles_RoleId FOREIGN KEY (RoleId) REFERENCES public.AspNetRoles(Id),
  CONSTRAINT FK_RolePermissions_Permissions_PermissionId FOREIGN KEY (PermissionId) REFERENCES public.Permissions(Id)
);
CREATE TABLE public.SavedPosts (
  Id uuid NOT NULL,
  UserId uuid NOT NULL,
  PostId uuid NOT NULL,
  CollectionName character varying,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT SavedPosts_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_SavedPosts_ProfessionalPosts_PostId FOREIGN KEY (PostId) REFERENCES public.ProfessionalPosts(Id)
);
CREATE TABLE public.ScheduleTemplates (
  Id uuid NOT NULL,
  DayOfWeek character varying NOT NULL,
  StartTime time without time zone NOT NULL,
  EndTime time without time zone NOT NULL,
  SlotDuration integer NOT NULL,
  MaxCapacity integer NOT NULL,
  Cost numeric,
  IsActive boolean NOT NULL DEFAULT true,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT ScheduleTemplates_pkey PRIMARY KEY (Id)
);
CREATE TABLE public.ScreeningResults (
  Id uuid NOT NULL,
  AiScreeningId uuid NOT NULL,
  RiskLevel character varying NOT NULL,
  Summary character varying,
  ConfidenceScore numeric NOT NULL,
  Findings character varying,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT ScreeningResults_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_ScreeningResults_AiScreenings_AiScreeningId FOREIGN KEY (AiScreeningId) REFERENCES public.AiScreenings(Id)
);
CREATE TABLE public.SlotAssignments (
  Id uuid NOT NULL,
  AppointmentSlotId uuid NOT NULL,
  StaffId uuid NOT NULL,
  Role character varying NOT NULL,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT SlotAssignments_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_SlotAssignments_AppointmentSlots_AppointmentSlotId FOREIGN KEY (AppointmentSlotId) REFERENCES public.AppointmentSlots(Id),
  CONSTRAINT FK_SlotAssignments_ClinicStaffs_StaffId FOREIGN KEY (StaffId) REFERENCES public.ClinicStaffs(Id)
);
CREATE TABLE public.SystemSettings (
  Key character varying NOT NULL,
  Value character varying NOT NULL,
  Description character varying,
  CONSTRAINT SystemSettings_pkey PRIMARY KEY (Key)
);
CREATE TABLE public.UserPermissions (
  Id uuid NOT NULL,
  UserId uuid NOT NULL,
  PermissionId uuid NOT NULL,
  GrantedBy uuid,
  GrantedAt timestamp with time zone NOT NULL,
  ExpiresAt timestamp with time zone,
  IsActive boolean NOT NULL DEFAULT true,
  IsGranted boolean NOT NULL DEFAULT true,
  CreatedAt timestamp with time zone NOT NULL,
  UpdatedAt timestamp with time zone,
  CreatedBy text,
  UpdatedBy text,
  IsDeleted boolean NOT NULL DEFAULT false,
  CONSTRAINT UserPermissions_pkey PRIMARY KEY (Id),
  CONSTRAINT FK_UserPermissions_Permissions_PermissionId FOREIGN KEY (PermissionId) REFERENCES public.Permissions(Id)
);
CREATE TABLE public.__EFMigrationsHistory (
  MigrationId character varying NOT NULL,
  ProductVersion character varying NOT NULL,
  CONSTRAINT __EFMigrationsHistory_pkey PRIMARY KEY (MigrationId)
);